#!/bin/bash

if [ "$1" == "install" ]; then 
    #npm install message 
    npm install fs > "mylog.txt" 2>&1
    npm install fs-extra > "mylog.txt" 2>&1 
    npm install isomorphic-git > "mylog.txt" 2>&1 
    npm install typescript > "mylog.txt" 2>&1 
    npm install @types/node > "mylog.txt" 2>&1 
    npm install axios > "mylog.txt" 2>&1 
    npm install tmp > "mylog.txt" 2>&1 
    npm install jest > "mylog.txt" 2>&1 
    npm install eslint > "mylog.txt" 2>&1 
    npm install @typescript-eslint/parser @typescript-eslint/eslint-plugin > "mylog.txt" 2>&1 
    npm install node-fetch@2 > "mylog.txt" 2>&1 
    npm install @octokit/graphql > "mylog.txt" 2>&1 
    npm install dotenv > "mylog.txt" 2>&1 
    npm install winston > "mylog.txt" 2>&1 
    npm install @types/jest ts-jest > "mylog.txt" 2>&1 
    npm install istanbul-lib-coverage istanbul-reports nyc > "mylog.txt" 2>&1 
    npm install @types/node-fetch > "mylog.txt" 2>&1 
    npm install jest-simple-summary-reporter
    echo "19 dependencies installed..."
elif [ "$1" == "test" ]; then
    npx jest --coverage > "jest.log.txt" 2>&1
    tsc src/run.ts
    node src/run.js "$@"
else
    tsc src/run.ts
    node src/run.js "$@"
fi
